field: e9f5b456-bc45-4b14-a51a-a14a9ffc13e3
fieldLayouts:
  3e43ac50-76f3-4fa5-a771-7b252bd34eea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b35860ec-5acb-4759-b2d6-cbf6e44b1a6c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 707422a1-aedc-4ddf-8707-292e8c51b6ad
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 83d38b79-d5d7-4f67-b731-76b5de770cac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fadfba90-3f65-4707-9dde-8781a7473f9a
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 32969fe3-afd1-4c5e-aca2-fda5b5276344
        userCondition: null
fields:
  83d38b79-d5d7-4f67-b731-76b5de770cac:
    columnSuffix: zlayrdom
    contentColumnType: text
    fieldGroup: null
    handle: manuellerWert
    instructions: null
    name: 'Manueller Wert'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b35860ec-5acb-4759-b2d6-cbf6e44b1a6c:
    columnSuffix: pylditjh
    contentColumnType: string(6)
    fieldGroup: null
    handle: hoehe
    instructions: null
    name: Höhe
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Klein
            -
              - value
              - klein
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Mittel
            -
              - value
              - mittel
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Groß
            -
              - value
              - gross
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: abstand
name: Abstand
sortOrder: 6
