field: e9f5b456-bc45-4b14-a51a-a14a9ffc13e3
fieldLayouts:
  bb5926fe-8b3a-4925-a3fc-7ca24b4b1c98:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 93963033-9406-4baa-8f7c-005bb4a4b4fd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c3628fa-e35a-4a18-8a52-df31b0ed82b1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9251ad0f-3882-432e-a2f8-985d2b4f6be0
        userCondition: null
fields:
  93963033-9406-4baa-8f7c-005bb4a4b4fd:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: hintergrundbild
    instructions: null
    name: Hintergrundbild
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:bab85a0a-a745-4104-aaff-e53e48734ff2'
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:bab85a0a-a745-4104-aaff-e53e48734ff2'
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: hero
name: Hero
sortOrder: 1
