field: e9f5b456-bc45-4b14-a51a-a14a9ffc13e3 # Matrix Inhalt
fieldLayouts:
  4f4a2bdd-488d-46f8-af09-38fb36804076:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc745822-7bdb-4017-9dcd-30ea5d884d12 # Inhalt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ce0e8e7-03e9-46b5-a0eb-d76905b1d612
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 73e70267-a7e4-4512-907f-3c4c67d8ff9a
        userCondition: null
fields:
  cc745822-7bdb-4017-9dcd-30ea5d884d12: # Inhalt
    columnSuffix: xjazgumd
    contentColumnType: text
    fieldGroup: null
    handle: inhalt
    instructions: null
    name: Inhalt
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 1
