field: e9f5b456-bc45-4b14-a51a-a14a9ffc13e3
fieldLayouts:
  a9eb5d79-a49c-4836-98c9-2768ae044677:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3ff75b84-f0d4-4363-8c05-52cdfa50768a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d40bec99-2d5a-4ed5-9127-98025a77d45e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f71a01d-139f-4546-be77-b15d92b87682
        userCondition: null
fields:
  3ff75b84-f0d4-4363-8c05-52cdfa50768a:
    columnSuffix: ieeaszru
    contentColumnType: text
    fieldGroup: null
    handle: inhalt
    instructions: null
    name: Inhalt
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ueberschrift
name: Überschrift
sortOrder: 2
