field: e9f5b456-bc45-4b14-a51a-a14a9ffc13e3 # Matrix Inhalt
fieldLayouts:
  9fe8c5d5-c1c6-4379-9ce3-772750d9a2a7:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 7a422107-febc-4aab-94ea-60526d69d208
        userCondition: null
handle: zweiSpalten
name: 'Zwei Spalten'
sortOrder: 5
