columnSuffix: trvwjeyu
contentColumnType: string(255)
fieldGroup: b6c6ba52-0ae9-4cbf-b647-98433d95e92f
handle: externerLink
instructions: null
name: 'Externer Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
