columnSuffix: null
contentColumnType: string
fieldGroup: b6c6ba52-0ae9-4cbf-b647-98433d95e92f
handle: internerLink
instructions: null
name: 'Interner Link'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
