defaultPlacement: end
enableVersioning: true
handle: inhalt
name: Inhalt
propagationMethod: all
siteSettings:
  328bbd2c-78c8-45d3-b9b1-9d5fe533f1c3:
    enabledByDefault: true
    hasUrls: true
    template: sites/proxy.html
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: af86249a-da80-4b84-9452-62e663f44cbd
type: structure
